core/urls.py
from django.urls import path

from core.api import (
    BoardColumnAndStatusApiVersion1,
    TicketColumStatusApiVersion1,
    ScrumBoardBacklogTicketUpdateApiVersion1,
    StartSprintEventApiVersion1,
    CompleteSprintEventApiVersion1,
    TicketOrderNoUpdateApiV1,
    TicketTypeListApiVersion1,
    TicketPriorityListApiVersion1,
    ColumnStatusListApiVersion1,
    ResolutionListApiVersion1,
    ProjectListApiVersion1,
    UserListApiVersion1,
    ProjectStatusListApiVersion1,
    LabelListApiVersion1,
)
from core.views import (
    loginView,
    registerView,
    logoutView,
    activateAccountView,
    forgotPasswordView,
    profileView,
    setPasswordView,
    teamsView,
    teamView,
    projectsView,
    projectView,
    boardsView,
    boardView,
    backlogView,
    boardSettingsView,
    labelsView,
    labelView,
    ticketsView,
    ticketView,
    newTicketView,
)

app_name = 'core'

urlpatterns = [
    path('login/', loginView, name='login-view'),
    path('register/', registerView, name='register-view'),
    path('logout/', logoutView, name='logout-view'),
    path('activate-account/<encodedId>/<token>', activateAccountView, name='activate-account-view'),
    path('forgot-password/', forgotPasswordView, name='forgot-password-view'),
    path('set-password/<encodedId>/<token>', setPasswordView, name='set-password-view'),
    path('profile/', profileView, name='profile-view'),
    path('teams/', teamsView, name='teams-view'),
    path('teams/<slug:url>/', teamView, name='team-view'),
    path('projects/', projectsView, name='projects-view'),
    path('projects/<slug:url>/', projectView, name='project-view'),
    path('boards/', boardsView, name='boards-view'),
    path('boards/<slug:url>/', boardView, name='board-view'),
    path('boards/<slug:url>/backlog', backlogView, name='board-backlog-view'),
    path('boards/<slug:url>/settings', boardSettingsView, name='board-settings-view'),
    path('labels/', labelsView, name='labels-view'),
    path('labels/<slug:url>/', labelView, name='label-view'),
    path('tickets/', ticketsView, name='tickets-view'),
    path('tickets/new/', newTicketView, name='new-ticket-view'),
    path('tickets/<slug:url>/', ticketView, name='ticket-view'),
]

urlpatterns += [
    path(
        'api/v1/boardColumnAndStatusApiVersion1/',
        BoardColumnAndStatusApiVersion1.as_view(),
        name='boardColumnAndStatusApiVersion1'
    ),
    path(
        'api/v1/ticketColumStatusApiVersion1/',
        TicketColumStatusApiVersion1.as_view(),
        name='ticketColumStatusApiVersion1'
    ),
    path(
        'api/v1/scrumBoardBacklogTicketUpdateApiVersion1/',
        ScrumBoardBacklogTicketUpdateApiVersion1.as_view(),
        name='scrumBoardBacklogTicketUpdateApiVersion1'
    ),
    path(
        'api/v1/startSprintEventApiVersion1/',
        StartSprintEventApiVersion1.as_view(),
        name='startSprintEventApiVersion1'
    ),
    path(
        'api/v1/completeSprintEventApiVersion1/',
        CompleteSprintEventApiVersion1.as_view(),
        name='completeSprintEventApiVersion1'
    ),
    path(
        'api/v1/ticketOrderNoUpdateApiV1/',
        TicketOrderNoUpdateApiV1.as_view(),
        name='ticketOrderNoUpdateApiV1'
    ),
    path(
        'api/v1/ticketTypeListApiVersion1/',
        TicketTypeListApiVersion1.as_view(),
        name='ticketTypeListApiVersion1'
    ),
    path(
        'api/v1/ticketPriorityListApiVersion1/',
        TicketPriorityListApiVersion1.as_view(),
        name='ticketPriorityListApiVersion1'
    ),
    path(
        'api/v1/columnStatusListApiVersion1/',
        ColumnStatusListApiVersion1.as_view(),
        name='columnStatusListApiVersion1'
    ),
    path(
        'api/v1/resolutionListApiVersion1/',
        ResolutionListApiVersion1.as_view(),
        name='resolutionListApiVersion1'
    ),
    path(
        'api/v1/projectListApiVersion1/',
        ProjectListApiVersion1.as_view(),
        name='projectListApiVersion1'
    ),
    path(
        'api/v1/userListApiVersion1/',
        UserListApiVersion1.as_view(),
        name='userListApiVersion1'
    ),
    path(
        'api/v1/projectStatusListApiVersion1/',
        ProjectStatusListApiVersion1.as_view(),
        name='projectStatusListApiVersion1'
    ),
    path(
        'api/v1/labelListApiVersion1/',
        LabelListApiVersion1.as_view(),
        name='labelListApiVersion1'
    ),
]

taskmaster/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('__reload__/', include('django_browser_reload.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    # Server statics and uploaded media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

core/models.py
import os
import random
import uuid

from colorfield.fields import ColorField
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


def getRandomAvatar():
    return 'avatars/' + random.choice(os.listdir(os.path.join(settings.MEDIA_ROOT, 'avatars/')))


def getRandomProjectIcon():
    return 'project-icons/' + random.choice(os.listdir(os.path.join(settings.MEDIA_ROOT, 'project-icons/')))


def getRandomString():
    return uuid.uuid4().hex[:8]


class BaseModel(models.Model):
    createdDateTime = models.DateTimeField(default=timezone.now)
    modifiedDateTime = models.DateTimeField(auto_now=True)
    orderNo = models.IntegerField(default=0)

    class Meta:
        abstract = True


class Profile(BaseModel):
    class JobTitle(models.TextChoices):
        SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER', _('Software Engineer')
        FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER', _('Frontend Developer')
        BACKEND_DEVELOPER = 'BACKEND_DEVELOPER', _('Backend Developer')
        DEVOPS_ENGINEER = 'DEVOPS_ENGINEER', _('DevOps Engineer')
        QA_ENGINEER = 'QA_ENGINEER', _('QA Engineer')
        PROJECT_OWNER = 'PROJECT_OWNER', _('Project Owner')
        PROJECT_MANAGER = 'PROJECT_MANAGER', _('Project Manager')
        SCRUM_MASTER = 'SCRUM_MASTER', _('Scrum Master')
        UX_UI_DESIGNER = 'UX_UI_DESIGNER', _('UX/UI Designer')
        SOLUTIONS_ARCHITECT = 'SOLUTIONS_ARCHITECT', _('Solutions Architect')
        BUSINESS_ANALYST = 'BUSINESS_ANALYST', _('Business Analyst')
        PRODUCT_MANAGER = 'PRODUCT_MANAGER', _('Product Manager')
        DATA_SCIENTIST = 'DATA_SCIENTIST', _('Data Scientist')
        INTERN = 'INTERN', _('Intern')

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING, related_name='profile')
    url = models.CharField(max_length=8, editable=False, unique=True, default=getRandomString)
    jobTitle = models.CharField(max_length=32, blank=True, null=True, choices=JobTitle.choices)
    department = models.CharField(max_length=128, blank=True, null=True)

    # icon = models.ImageField(upload_to='profile-picture', blank=True, null=True, default=getRandomAvatar)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return self.user.get_full_name()


class Team(BaseModel):
    name = models.CharField(max_length=128, unique=True)
    url = models.CharField(max_length=8, editable=False, unique=True, default=getRandomString)
    description = models.TextField()
    isPrivate = models.BooleanField(default=False)
    admins = models.ManyToManyField(User, blank=True, related_name='teamAdmins')
    members = models.ManyToManyField(User, blank=True, related_name='teamMembers')

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

    def __str__(self):
        return self.name

    def hasViewPermission(self, user):
        if not self.isPrivate:
            return True
        return user in self.members.all() or user in self.admins.all()


class Project(BaseModel):
    class Status(models.TextChoices):
        ACTIVE = 'ACTIVE', _('Active')
        IN_PROGRESS = 'IN_PROGRESS', _('In Progress')
        ON_HOLD = 'ON_HOLD', _('On Hold')
        COMPLETED = 'COMPLETED', _('Completed')
        CANCELLED = 'CANCELLED', _('Cancelled')
        TERMINATED = 'TERMINATED', _('Terminated')
        DRAFT = 'DRAFT', _('Draft')
        INACTIVE = 'INACTIVE', _('Inactive')
        PENDING = 'PENDING', _('Pending')
        ARCHIVED = 'ARCHIVED', _('Archived')
        DELAYED = 'DELAYED', _('Delayed')
        APPROVED = 'APPROVED', _('Approved')
        REJECTED = 'REJECTED', _('Rejected')
        WAITING_FOR_FEEDBACK = 'WAITING_FOR_FEEDBACK', _('Waiting for Feedback')
        UNDER_REVIEW = 'UNDER_REVIEW', _('Under Review')
        READY_FOR_REVIEW = 'READY_FOR_REVIEW', _('Ready for Review')

    name = models.CharField(max_length=128, unique=True)
    code = models.CharField(max_length=8, unique=True)
    url = models.CharField(max_length=8, editable=False, unique=True, default=getRandomString)
    description = models.TextField()
    startDate = models.DateField(default=timezone.now)
    endDate = models.DateField(default=timezone.datetime.max)
    status = models.CharField(max_length=32, blank=True, null=True, choices=Status.choices)
    isPrivate = models.BooleanField(default=False)
    lead = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    members = models.ManyToManyField(User, blank=True, related_name='projectMembers')

    # icon = models.ImageField(upload_to='project-icons/', default=getRandomProjectIcon)

    class Meta:
        verbose_name = 'Project'
        verbose_name_plural = 'Projects'

    def __str__(self):
        return self.name

    def hasViewPermission(self, user):
        if not self.isPrivate:
            return True
        return user == self.lead or user in self.members.all()


class Board(BaseModel):
    class Types(models.TextChoices):
        SCRUM = 'SCRUM', _('Scrum')
        KANBAN = 'KANBAN', _('Kanban')

    name = models.CharField(max_length=128, unique=True)
    url = models.CharField(max_length=8, editable=False, unique=True, default=getRandomString)
    type = models.CharField(max_length=8, choices=Types.choices, default=Types.KANBAN)
    isPrivate = models.BooleanField(default=False)
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING, related_name='boardProjects')
    admins = models.ManyToManyField(User, blank=True, related_name='boardAdmins')
    members = models.ManyToManyField(User, blank=True, related_name='boardMembers')

    class Meta:
        verbose_name = 'Board'
        verbose_name_plural = 'Boards'

    def __str__(self):
        return self.name

    def hasViewPermission(self, user):
        if not self.isPrivate:
            return True
        return user in self.members.all() or user in self.admins.all()

    @property
    def getUrl(self):
        return reverse('core:board-view', kwargs={'url': self.url})


class Label(BaseModel):
    class Colour(models.TextChoices):
        BLUE = '#669df1', _('Blue')
        TEAL = '#6cc3e0', _('Teal')
        GREEN = '#4bce97', _('Green')
        LIME = '#94c748', _('Lime')
        YELLOW = '#eed12b', _('Yellow')
        PURPLE = '#c97cf4', _('Purple')
        MAGENTA = '#e774bb', _('Magenta')
        RED = '#f87168', _('Red')
        ORANGE = '#fca700', _('Orange')
        GRAY = '#8c8f97', _('Gray')
    name = models.CharField(max_length=128, unique=True)
    description = models.CharField(max_length=1024, blank=True, null=True)
    url = models.CharField(max_length=8, editable=False, unique=True, default=getRandomString)
    colour = models.CharField(max_length=8, blank=True, null=True, choices=Colour.choices)

    class Meta:
        verbose_name = 'Label'
        verbose_name_plural = 'Labels'

    def __str__(self):
        return self.name


class Column(BaseModel):
    class Status(models.TextChoices):
        UNMAPPED = 'UNMAPPED', _('Unmapped')
        BACK_LOG = 'BACK_LOG', _('Back Log')
        TODO = 'TODO', _('To Do')
        IN_PROGRESS = 'IN_PROGRESS', _('In Progress')
        DONE = 'DONE', _('Done')

    name = models.CharField(max_length=32)
    board = models.ForeignKey(Board, on_delete=models.DO_NOTHING, related_name='boardColumns')
    status = models.CharField(max_length=16, blank=True, null=True, choices=Status.choices)

    class Meta:
        verbose_name = 'Column'
        verbose_name_plural = 'Columns'
        ordering = ['orderNo']

    def __str__(self):
        return self.name

    def getColour(self):
        if self.status == self.Status.UNMAPPED:
            return '#42526E'
        elif self.status == self.Status.BACK_LOG:
            return '#42526E'
        elif self.status == self.Status.TODO:
            return '#42526E'
        elif self.status == self.Status.IN_PROGRESS:
            return '#0052CC'
        elif self.status == self.Status.DONE:
            return '#00875A'
        raise NotImplemented

    def save(self, *args, **kwargs):
        isNew = self.pk is None
        super().save(*args, **kwargs)

        if isNew:
            self.orderNo = self.pk
            super().save(update_fields=['orderNo'])


class ColumnStatus(BaseModel):
    name = models.CharField(max_length=32)
    column = models.ForeignKey(Column, on_delete=models.DO_NOTHING, related_name='columnStatus')

    class Meta:
        verbose_name = 'ColumnStatus'
        verbose_name_plural = 'ColumnStatus'
        ordering = ['orderNo']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        isNew = self.pk is None
        super().save(*args, **kwargs)

        if isNew:
            self.orderNo = self.pk
            super().save(update_fields=['orderNo'])


class Ticket(BaseModel):
    class Resolution(models.TextChoices):
        UNRESOLVED = 'UNRESOLVED', _('Unresolved')  # Default, unresolved state
        FIXED = 'FIXED', _('Fixed')  # Issue has been resolved via a fix
        WONT_FIX = 'WONT_FIX', _('Won\'t Fix')  # Valid issue, but won’t be addressed
        DUPLICATE = 'DUPLICATE', _('Duplicate')  # Same as another ticket
        INCOMPLETE = 'INCOMPLETE', _('Incomplete')  # Not enough info to act
        CANNOT_REPRODUCE = 'CANNOT_REPRODUCE', _('Cannot Reproduce')  # Could not replicate issue
        NOT_A_BUG = 'NOT_A_BUG', _('Not a Bug')  # Intended behavior or non-defect
        POSTPONED = 'POSTPONED', _('Postponed')  # Deferred for future
        RESOLVED = 'RESOLVED', _('Resolved')  # General “done” status
        CLOSED = 'CLOSED', _('Closed')  # Explicitly marked as done, with or without fix
        REOPENED = 'REOPENED', _('Reopened')  # Issue reoccurred or wrongly resolved

core/templates/core/boards.html
{% extends "core/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% load templateTags %}
{% block content %}
    <div class="container d-flex justify-content-center mt-5 mb-5" style="color: black;">
        <div class="card idCardWideComponent">
            <legend>
                <h2 class="heading-h2 text-center">Boards</h2>
                <button type="button" class="btn btn-sm float-right mr-2" id="add-board-btn">Add Board</button>
            </legend>
            <form method="post" class="p-4" id="form-id-new-board"
                  style="display: {% if form.errors %}block{% else %}none{% endif %}">
                {% csrf_token %}
                {% for field in form %}
                    {% renderFormFields field %}
                    {% for error in field.errors %}
                        <p class="text-center" style="color: red;"><small>{{ error }}</small></p>
                    {% endfor %}
                    <br>
                {% endfor %}

                <div class="text-right">
                    <input type="button" class="btn btn-sm btn-cancel" id="close-board-btn" value="Cancel">
                    <input type="submit" class="btn btn-sm btn-submit" value="Submit">
                </div>
            </form>

            <div class="form-row align-items-center mt-4 flex-nowrap">
                <div class="col-2">
                    <input type="text" name="query" class="form-control form-control-sm" placeholder="Search"
                           value="{{ request.GET.query }}">
                </div>
                <div class="col d-flex justify-content-between" id="filter-list"></div>
                <div class="col-auto ml-auto d-flex align-items-center float-right" id="filter-toggle-container">
                    <button type="button" class="btn btn-sm btn-submit">
                        Search
                    </button>
                </div>
            </div>

            <table id="boardsTable" class="table table-sm table-bordered table-hover" style="width: 100%">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Admins</th>
                    <th>Members</th>
                    <th>Type</th>
                    <th>Visibility</th>
                    <th>Project</th>
                </tr>
                </thead>
                <tbody>
                {% for board in boards %}
                    <tr>
                        <td>
                            <a href="{% url 'core:board-view' url=board.url %}">{{ board.name }}</a>
                        </td>
                        <td>
                            {% renderSingleOrGroupUserAvatars board.admins.all %}
                        </td>
                        <td>
                            {% renderSingleOrGroupUserAvatars board.members.all %}
                        </td>
                        <td>
                            <span class="badge badge-{% if board.type == 'KANBAN' %}primary{% else %}secondary{% endif %}">
                                {{ board.get_type_display }}
                            </span>
                        </td>
                        <td>
                            <span class="badge badge-{% if board.isPrivate %}danger{% else %}success{% endif %}">
                                {% if board.isPrivate %}Private{% else %}Public{% endif %}
                            </span>
                        </td>
                        <td>
                            <a href="{% url 'core:project-view' url=board.project.url %}">{{ board.project.name }}</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% paginationComponent request boards %}
        </div>
    </div>

    <script src="{% static 'js/multi-filter-controller.js' %}"></script>
    <script type="application/javascript">
        function initialiseBoardForm() {
            const newBoardBtn = document.getElementById('add-board-btn');
            const closeBoardBtn = document.getElementById('close-board-btn');
            const newBoardForm = document.getElementById('form-id-new-board');

            newBoardBtn.addEventListener('click', function () {
                newBoardForm.style.display = (newBoardForm.style.display === 'none' || newBoardForm.style.display === '') ? 'block' : 'none';
            });

            closeBoardBtn.addEventListener('click', function () {
                newBoardForm.style.display = 'none';
            });

        }

        function initialiseDataTable() {
            $("#boardsTable").DataTable({
                responsive: true,
                autoWidth: true,
                paging: false,
                searching: false,
                ordering: true,
                info: false,
                scrollX: true,
            });
        }

        function initialiseSelect2() {
            document.querySelectorAll('.select2bs4').forEach(selectElement => {
                $(selectElement).select2();
            });
        }

        function runSearch(filter) {
            const query = document.querySelector('[name="query"]').value.trim();
            const params = new URLSearchParams();
            if (query) params.append('query', query);

            const selections = filter.getSelections();
            Object.keys(selections).forEach(k => params.append(k, selections[k].join(',')));
            window.location.href = `${'{% url "core:boards-view" %}'}?${params.toString()}`;
        }

        document.addEventListener('DOMContentLoaded', function () {
            initialiseBoardForm();
            initialiseDataTable();
            initialiseSelect2();

            const filter = new MultiFilterController({
                filterListEl: document.getElementById('filter-list'),
                filterToggleContainerEl: document.getElementById('filter-toggle-container'),
                filters: [
                    {
                        name: 'admins',
                        urlParam: 'admins',
                        fetchUrl: '{% url "core:userListApiVersion1" %}'
                    },
                    {
                        name: 'members',
                        urlParam: 'members',
                        fetchUrl: '{% url "core:userListApiVersion1" %}'
                    },
                    {
                        name: 'type',
                        urlParam: 'type',
                        data: [{key: 'KANBAN', value: 'Kanban'}, {key: 'SCRUM', value: 'Scrum'}]
                    },
                    {
                        name: 'visibility',
                        urlParam: 'visibility',
                        data: [{key: 'PUBLIC', value: 'Public'}, {key: 'PRIVATE', value: 'Private'}]
                    },
                    {
                        name: 'project',
                        urlParam: 'project',
                        fetchUrl: '{% url "core:projectListApiVersion1" %}'
                    }
                ]
            });

            document.querySelector('#filter-toggle-container .btn-submit').addEventListener('click', () => {
                runSearch(filter);
            });

            document.querySelector('input[name="query"]').addEventListener('keydown', function (event) {
                if (event.key === 'Enter') {
                    runSearch(filter);
                }
            });

        });
    </script>
{% endblock %}

core/templates/core/login.html
{% extends "core/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% load templateTags %}
{% block content %}
    <div class="container d-flex justify-content-center mt-5" style="color: black;">
        <div class="card idCardNarrowComponent">
            <legend>
                <h2 class="heading-h2 text-center">Login</h2>
            </legend>
            <form method="post" class="p-4">
                {% csrf_token %}
                {% for field in form %}
                    {% renderFormFields field %}
                    {% for error in field.errors %}
                        <p class="text-center" style="color: red;"><small>{{ error }}</small></p>
                    {% endfor %}
                    <br>
                {% endfor %}

                <div class="text-right">
                    <input type="reset" class="btn btn-sm btn-reset" value="Reset">
                    <input type="submit" class="btn btn-sm btn-submit" value="Submit">
                </div>
            </form>
            <div class="text-muted text-center">
                Forgot your password? <a href="{% url 'core:forgot-password-view' %}">Reset Here</a>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/tickets.html
{% extends "core/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}
{% load templateTags %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/avatars-icons.css' %}"/>
    <div class="container-fluid justify-content-center mt-5 mb-5" style="color: black;">
        <div class="card idCardWideComponent">
            <legend>
                <h2 class="heading-h2 text-center">Tickets</h2>
            </legend>

            <div class="form-row align-items-center mt-4 flex-nowrap">
                <div class="col-2">
                    <input type="text" name="query" class="form-control form-control-sm" placeholder="Search"
                           value="{{ request.GET.query }}">
                </div>
                <div class="col d-flex justify-content-between" id="filter-list"></div>
                <div class="col-auto ml-auto d-flex align-items-center float-right" id="filter-toggle-container">
                    <button type="button" class="btn btn-sm btn-submit">
                        Search
                    </button>
                </div>
            </div>

            <table id="ticketsTable" class="table table-sm table-bordered table-hover display nowrap"
                   style="width: 100%">
                <thead>
                <tr>
                    <th>T</th>
                    <th>Key</th>
                    <th>Summary</th>
                    <th>Assignee</th>
                    <th>Reporter</th>
                    <th>P</th>
                    <th>Status</th>
                    <th>Resolution</th>
                    <th>Labels</th>
                    <th>Created date</th>
                    <th>Updated Date</th>
                </tr>
                </thead>
                <tbody>
                {% for ticket in tickets %}
                    <tr>
                        <td>
                            <img src="{{ ticket.ticketTypeIcon }}" width="20px"
                                 title={{ ticket.get_type_display }} class="img-rounded" loading="lazy"
                                 style="margin-left: 10px"/>
                            <span style="display: none;">{{ ticket.get_type_display }}</span>
                        </td>
                        <td>{{ ticket.url }}</td>
                        <td>
                            <a href="{{ ticket.getUrl }}">{{ ticket.summary }}</a>
                        </td>
                        <td>
                            {% renderSingleOrGroupUserAvatars ticket.assignee %}
                        </td>
                        <td>
                            {% renderSingleOrGroupUserAvatars ticket.reporter %}
                        </td>
                        <td>
                            <img src="{{ ticket.ticketPriorityIcon }}" width="20px"
                                 title={{ ticket.get_priority_display }} class="img-rounded" loading="lazy"
                                 style="margin-left: 10px"/>
                            <span style="display: none;">{{ ticket.get_priority_display }}</span>
                        </td>
                        <td>
                            <h6>
                                <span class="badge"
                                      style="background-color: {{ ticket.columnStatus.column.getColour }}; color: white;">
                                    {{ ticket.columnStatus.name }}
                                </span>
                            </h6>
                        </td>
                        <td>{{ ticket.get_resolution_display }}</td>
                        <td>
                            {% for label in ticket.label.all %}
                                <a href="#"
                                   class="badge badge-light border"
                                   style="background-color: {{ label.colour }}; color: white">{{ label.name }}</a>
                            {% endfor %}
                        </td>
                        <td>{{ ticket.createdDateTime|date:"d M Y" }}</td>
                        <td>{{ ticket.modifiedDateTime|date:"d M Y" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% paginationComponent request tickets %}
        </div>
    </div>

    <script src="{% static 'js/multi-filter-controller.js' %}"></script>
    <script type="application/javascript">

        function initialiseDataTable() {
            $("#ticketsTable").DataTable({
                responsive: true,
                autoWidth: true,
                paging: false,
                searching: false,
                ordering: true,
                info: false,
                scrollX: true,
            });
        }

        function runSearch(filter) {
            const query = document.querySelector('[name="query"]').value.trim();
            const params = new URLSearchParams();
            if (query) params.append('query', query);

            const selections = filter.getSelections();
            Object.keys(selections).forEach(k => params.append(k, selections[k].join(',')));
            window.location.href = `${'{% url "core:tickets-view" %}'}?${params.toString()}`;
        }

        document.addEventListener('DOMContentLoaded', function () {
            initialiseDataTable();

            const filter = new MultiFilterController({
                filterListEl: document.getElementById('filter-list'),
                filterToggleContainerEl: document.getElementById('filter-toggle-container'),
                filters: [
                    {
                        name: 'type',
                        urlParam: 'type',
                        fetchUrl: '{% url "core:ticketTypeListApiVersion1" %}'
                    },
                    {
                        name: 'priority',
                        urlParam: 'priority',
                        fetchUrl: '{% url "core:ticketPriorityListApiVersion1" %}'
                    },
                    {
                        name: 'status',
                        urlParam: 'status',
                        fetchUrl: '{% url "core:columnStatusListApiVersion1" %}'
                    },
                    {
                        name: 'resolution',
                        urlParam: 'resolution',
                        fetchUrl: '{% url "core:resolutionListApiVersion1" %}'
                    },
                    {
                        name: 'project',
                        urlParam: 'project',
                        fetchUrl: '{% url "core:projectListApiVersion1" %}'
                    },
                    {
                        name: 'assignee',
                        urlParam: 'assignee',
                        fetchUrl: '{% url "core:userListApiVersion1" %}'
                    },
                    {
                        name: 'reporter',
                        urlParam: 'reporter',
                        fetchUrl: '{% url "core:userListApiVersion1" %}'
                    },
                    {
                        name: 'label',
                        urlParam: 'label',
                        fetchUrl: '{% url "core:labelListApiVersion1" %}'
                    },
                ]
            });

            document.querySelector('#filter-toggle-container .btn-submit').addEventListener('click', () => {
                runSearch(filter);
            });

            document.querySelector('input[name="query"]').addEventListener('keydown', function (event) {
                if (event.key === 'Enter') {
                    runSearch(filter);
                }
            });
        });

    </script>
{% endblock %}